// Code generated by mockery v2.33.3. DO NOT EDIT.

package mocks

import (
	admins "Hannon-app/features/admins"

	mock "github.com/stretchr/testify/mock"
)

// AdminData is an autogenerated mock type for the AdminDataInterface type
type AdminData struct {
	mock.Mock
}

// Login provides a mock function with given fields: email, password
func (_m *AdminData) Login(email string, password string) (admins.AdminCore, error) {
	ret := _m.Called(email, password)

	var r0 admins.AdminCore
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (admins.AdminCore, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) admins.AdminCore); ok {
		r0 = rf(email, password)
	} else {
		r0 = ret.Get(0).(admins.AdminCore)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdminData creates a new instance of AdminData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminData(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminData {
	mock := &AdminData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
